name:                sample-hs-lambda
version:             0.1.0
github:              "luvemil/sample-hs-lambda-public"
license:             BSD3
author:              "Marco Tarantino"
maintainer:          "taran.marco@protonmail.com"
copyright:           "2022 Marco Tarantino"

description:         Please see the README on GitHub at <https://github.com/luvemil/sample-hs-lambda#readme>

dependencies:
- base >= 4.7 && < 5
- aws-lambda-haskell-runtime >= 3.0.0
- aeson

library:
  source-dirs: src

executables:
  bootstrap:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    - -with-rtsopts=-N
    dependencies:
    - sample-hs-lambda

default-extensions:
  - RecordWildCards
  - OverloadedLists
  - OverloadedStrings
  - DeriveGeneric
